FROM randomdude/gcc-cross-x86_64-elf

RUN apt-get update 
RUN apt-get upgrade -y
RUN apt-get install -y byacc 
RUN apt-get install -y flex 

VOLUME /Users/Macky/Macky/program/cpp
WORKDIR /Users/Macky/Macky/program/cpp